### PR TITLE
fix: wrong balance err check

### LINKED ISSUE #383: bug:  wrong balance check in solver's addResourceOffer api
### Describe the bug

wrong balance check in solver's addResourceOffer api.  this has led to endless RP requests

### Reproduction

this exist in current deploy

### Logs

_No response_

### Screenshots

_No response_

### System Info

```shell
linux
```

### Severity

Annoyance

### PR DESCRIPTION
**Pull request by hunjixin**
### Summary

This pull request makes the following changes:

- [ ] fix error check in solver

Explain the motivation for making these changes. Does this pull request implement a feature or fix a bug? Is it a docs change or a typo fix?

### Task/Issue reference

Closes: https://github.com/Lilypad-Tech/lilypad/issues/383

### Test plan

Please describe how reviewers can test the changes in this pull request. If the test plan is challenging to explain in text alone, a short video demonstration may be included.

### Details (optional)

Add any additional details that will help to review this pull request.

### Related issues or PRs (optional)

Add any related issues or PRs.

### CODE REVIEW

File: pkg/solver/controller.go [hunk 1]
```diff
@@ -331,7 +331,7 @@ func (controller *SolverController) addResourceOffer(resourceOffer data.Resource
 	requiredBalanceWei := web3.EtherToWei(float64(resourceOffer.DefaultPricing.InstructionPrice))
 	// If the balance is less than the required balance, don't add the resource offer
 	if balance.Cmp(requiredBalanceWei) < 0 {
-		return nil, err
+		return nil, fmt.Errorf("address %s dont has enough balance expect %s but only have %s", resourceOffer.ResourceProvider, requiredBalanceWei, balance)
```
Comment (walkah) [inline pkg/solver/controller.go]:
```suggestion
		return nil, fmt.Errorf("address %s doesn't have enough funds. required balance is %s but expected balance is %s", resourceOffer.ResourceProvider, requiredBalanceWei, balance)
```

**Review by walkah — APPROVED** [review]
Good catch @hunjixin ! I suggested some minor english phrasing changes.

**Review by narbs91 — APPROVED** [review]
LGTM!  I think the only thing is @walkah 's suggested edit and then this is good to go
